import { useState } from 'react';
import { ArrowRight, ArrowUpRight, AudioLines, Check, ChevronRight, CircleDot, Cpu, GitBranch, Laptop, Link2, MessageSquare, Plus, QrCode, Radio, ShieldCheck, Terminal, Zap } from 'lucide-react';
import { usePocket } from '../store/PocketProvider';
import { CoreArt } from '../components/Brand';
import { Button, EmptyState } from '../components/ui';
import { NewSession, SessionRow } from '../components/SessionList';
import { folderName } from '../lib/format';

export function Overview() {
  const { data, client, status, version, pendingCount, connectedModels, setScreen, setConnectOpen, preferences, openSession } = usePocket();
  const [newOpen, setNewOpen] = useState(false);
  const active = Object.values(data.statuses).filter((item) => item.type === 'busy' || item.type === 'retry').length;
  const recent = data.sessions.filter((item) => !item.time.archived).sort((a,b) => b.time.updated - a.time.updated).slice(0, 5);
  const pending = [...data.questions, ...data.permissions][0];
  const pendingSession = data.sessions.find((item) => item.id === pending?.sessionID);
  return <div className="page overview-page">
    <div className="overview-topline"><span className="eyebrow"><span className="tiny-square"/>ТВОЯ ПЕРСОНАЛЬНАЯ ИНЖЕНЕРНАЯ ЛАБОРАТОРИЯ</span><span className="mono overview-date">{new Date().toLocaleDateString('en', { month: 'short', day: '2-digit', year: 'numeric' }).toUpperCase()}</span></div>
    <section className="hero panel"><div className="hero-copy"><span className="hero-kicker"><span className="live-dot"/>CODE / ANYWHERE / ANYTIME</span><h1>Твой код.<br/><em>Всегда рядом.</em></h1><p>Большие идеи не привязаны к столу.<br/>Продолжай в OpenCode с того же места.</p><Button onClick={() => client ? setNewOpen(true) : setConnectOpen(true)}>{client ? <Plus size={18}/> : <Link2 size={18}/>}<span>{client ? 'Начать сессию' : 'Подключить компьютер'}</span><ArrowUpRight size={18}/></Button></div><CoreArt/><span className="hero-index mono">OCC — 001 / POCKET EDITION</span></section>
    <div className="metric-grid"><div className="metric-card"><div className="metric-label"><Terminal size={16}/><span>Сессии в работе</span></div><div className="metric-value">{String(active).padStart(2, '0')}<span className="metric-note"><span className={active ? 'live-dot' : 'neutral-dot'}/>{active ? 'Прямо сейчас' : 'Всё спокойно'}</span></div><div className="metric-rule"><span style={{ width: active ? `${Math.min(active * 14, 100)}%` : '0%' }}/></div></div>
      <button className="metric-card metric-clickable" onClick={() => setScreen('inbox')}><div className="metric-label"><MessageSquare size={16}/><span>Нужно твоё решение</span><ArrowUpRight size={14}/></div><div className="metric-value">{String(pendingCount).padStart(2, '0')}<span className="metric-note">{pendingCount ? 'Ждут ответа' : 'Ничего не ждёт'}</span></div><div className="metric-rule warm"><span style={{ width: pendingCount ? '44%' : '0%' }}/></div></button>
      <button className="metric-card metric-clickable" onClick={() => setScreen('models')}><div className="metric-label"><Cpu size={16}/><span>Модели на связи</span><ArrowUpRight size={14}/></div><div className="metric-value">{String(connectedModels.length).padStart(2, '0')}<span className="metric-note">{connectedModels.length ? 'Готовы к работе' : 'После подключения'}</span></div><div className="metric-rule"><span style={{ width: connectedModels.length ? '78%' : '0%' }}/></div></button></div>
    <div className="dashboard-grid"><section className="panel recent-panel"><div className="panel-title"><div><span className="eyebrow">WORK IN PROGRESS</span><h2>Продолжить работу</h2></div><button className="subtle-link" onClick={() => setScreen('sessions')}>Все сессии<ArrowRight size={15}/></button></div>
      {recent.length ? recent.map((session) => <SessionRow key={session.id} session={session}/>) : <EmptyState icon={<GitBranch size={29}/>} title="Твой следующий коммит — отсюда">{client ? 'Начни новую сессию: план, код, проверка — всё доступно с телефона.' : 'После подключения здесь появятся сессии с компьютера. Весь контекст уже на месте.'}</EmptyState>}
      <button className="panel-bottom-action" onClick={() => client ? setNewOpen(true) : setConnectOpen(true)}><Plus size={16}/>{client ? 'Что-нибудь новое?' : 'Добавить первое подключение'}<ArrowRight size={16}/></button>
    </section><div className="dashboard-aside"><section className="panel connection-card"><div className="panel-title compact"><span className="eyebrow">ТВОЙ КОМПЬЮТЕР</span><Radio size={16} className={status === 'live' ? 'accent' : 'muted'}/></div><div className="machine-icon"><Laptop size={34}/><span className={status === 'live' ? 'machine-dot online' : 'machine-dot'}/></div><h3>{client?.connection.name ?? 'Ждёт подключения'}</h3><p className="mono connection-address">{client ? new URL(client.connection.url).hostname : 'DESKTOP → POCKET'}</p><div className="machine-status"><span className={status === 'live' ? 'live-dot' : 'neutral-dot'}/>{status === 'live' ? `OpenCode ${version}` : client ? 'Восстанавливаем связь…' : 'Без облачной учётной записи'}</div><Button variant="secondary" onClick={() => setConnectOpen(true)}>{client ? 'Подключения' : 'Подключить'}<ChevronRight size={16}/></Button></section>
      <button className="voice-card" onClick={() => pendingSession ? openSession(pendingSession) : setScreen('settings')}><div className="voice-card-top">{pendingCount ? <MessageSquare size={20}/> : <AudioLines size={21}/>}<ArrowUpRight size={16}/></div><h3>{pendingCount ? 'Нужен твой ответ' : 'Мысль → голос → код'}</h3><p>{pendingCount ? `${pendingCount} запроса. ${pendingSession ? folderName(pendingSession.directory) : 'Откройте входящие'}, чтобы продолжить.` : 'Надиктуй идею. Системное распознавание превратит её в промпт.'}</p><span className="eyebrow">{pendingCount ? 'ПРОДОЛЖИТЬ СЕССИЮ' : preferences.offlineSpeech ? 'ON-DEVICE / PRIVATE' : 'SYSTEM SPEECH'}</span></button>
    </div></div>
    {!client && <section className="setup-steps"><div><span className="step-number">01</span><Terminal size={20}/><h3>Один плагин</h3><p>Установи OCC-мост в OpenCode.</p></div><div><span className="step-number">02</span><QrCode size={20}/><h3>Один QR-код</h3><p>Свяжи телефон с компьютером.</p></div><div><span className="step-number">03</span><Zap size={20}/><h3>Ты на связи</h3><p>Промпты, модели, вопросы. Везде.</p></div></section>}
    <footer className="workspace-footer"><span><ShieldCheck size={14}/>Твой сервер. Твои правила.</span><span className="mono"><CircleDot size={12}/> VIBE IN. SYSTEMS OUT.</span><span className="footer-connected"><Check size={13}/> MADE BY HVHBIGNAME</span></footer>
    {newOpen && <NewSession onClose={() => setNewOpen(false)}/>}
  </div>;
}
